# Generated by Django 4.1.5 on 2023-01-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text="Client's nickname", max_length=50, unique=True)),
                ('realname', models.CharField(help_text="Client's name", max_length=255)),
                ('secondname', models.CharField(help_text="Client's secondname", max_length=255)),
                ('patronymic', models.CharField(help_text="Client's patronymic", max_length=255)),
                ('email', models.CharField(help_text="Client's email", max_length=320, unique=True)),
                ('password', models.CharField(help_text='SHA256 hash of password', max_length=64)),
                ('rights', models.IntegerField(default=0, help_text='Rights of the client')),
                ('dateins', models.DateTimeField(auto_now_add=True, help_text='Date when the row was append')),
                ('datechange', models.DateTimeField(blank=True, help_text='Date when the row was changed')),
                ('fromIP', models.CharField(help_text="Client's last login IP", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themename', models.CharField(help_text='Name of the theme', max_length=512, unique=True)),
                ('datechange', models.DateTimeField(blank=True, help_text='Date when the row was changed')),
            ],
        ),
        migrations.CreateModel(
            name='quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizname', models.CharField(help_text='Name of the quiz', max_length=512, unique=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration of tests')),
                ('countofquestions', models.IntegerField(default=0, help_text='ammount of questions in this test')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.clients')),
                ('themeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.themes')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question', max_length=1024)),
                ('qtype', models.PositiveSmallIntegerField(default=0, help_text='Type of question')),
                ('sequence', models.IntegerField(default=0, help_text='Order for submitting questions')),
                ('version', models.IntegerField(default=0, help_text='Test version')),
                ('weight', models.FloatField(default=0, help_text='Test version')),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.clients')),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0, help_text='Number of attempts')),
                ('version', models.IntegerField(default=0, help_text='Test version')),
                ('randomseq', models.BooleanField(default=0, help_text='is sequence random')),
                ('randomver', models.BooleanField(default=0, help_text='is variant random')),
                ('maxpoints', models.IntegerField(default=0, help_text='maximum possible points')),
                ('duration', models.IntegerField(default=0, help_text='duration of the test')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.clients')),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.assignment')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.questions')),
            ],
        ),
    ]
