# Generated by Django 4.1.5 on 2023-01-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='assignmentID',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='', help_text='Question', max_length=1024),
        ),
        migrations.AddField(
            model_name='answers',
            name='iscorrect',
            field=models.PositiveSmallIntegerField(default=0, help_text='is answer correct'),
        ),
        migrations.AddField(
            model_name='answers',
            name='recorrect',
            field=models.CharField(default='', help_text='Regular expression to correct the response', max_length=255),
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.assignment')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.questions')),
            ],
        ),
    ]
