# Generated by Django 4.1.5 on 2023-03-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0003_alter_assignment_clientid_alter_editors_clientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='themeID',
        ),
        migrations.DeleteModel(
            name='themes',
        ),
    ]
