# Generated by Django 4.1.5 on 2023-03-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0004_remove_quizzes_themeid_delete_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='qtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(help_text='Question type', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='qtype',
        ),
        migrations.AddField(
            model_name='questions',
            name='qtypeID',
            field=models.ForeignKey(default=1, help_text='Type of question', on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.qtype'),
            preserve_default=False,
        ),
    ]
