# Generated by Django 4.1.5 on 2023-03-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0005_qtype_remove_questions_qtype_questions_qtypeid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qtype',
            new_name='qtypes',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='qtypeID',
            new_name='qtypesID',
        ),
    ]
